apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-dep
  namespace: dev #namespace를 설정 합니다.
  labels:
    app: namespace-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: namespace-nginx
  template:
    metadata:
      labels:
        app: namespace-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
