apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-dep-1
  labels:
    app: namespace-nginx-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: namespace-nginx-1
  template:
    metadata:
      labels:
        app: namespace-nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
