apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: pod-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2      
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    run: nginx-nodeport
spec:
  type: NodePort     # 서비스 타입
  selector:
    app: pod-nginx
  ports:
  - targetPort: 80   # pod에서 open된 port
    port: 80         # Pod와 연결된 service port
    nodePort: 30008  # service와 연결된 node의 port
