apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cluster
spec:
  selector:
    matchLabels:
      app: nginx-cluster
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-cluster
    spec:
      containers:
      - name: nginx-cluster
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cl-nginx
spec:
  selector:
    app: nginx-cluster
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP


