apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    test: MyApp
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
      name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    test: MyApp
  ports:
  - port: 80
    targetPort: 80
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30007
