apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: test-user
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF3d0pkR1Z6ZEMxMWMyVnlNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEraXlZTHZBUWJEVE9KZXdEc2ZiQ2VkOGtSZUtZWjFUODFFYmdtNk1PCkZENWR2M3BtdHRKVzZ2NEloUC9IaTdkR3NOSE1WbWFzQkhsUTdlZXR2RVhXZXkvcE1UZHlpMXJnZGoxbkFvK2UKSVRxUldXUWd2VHJiUWxDMTBNRUFJbTRhT1lkM1RLOFFxcGJrS0NlYlVYVjJ0a1Zza2hwalgzU3pvOTRGcHlYQQpNOEtOcHQwS0lxK211TXNsUDhIYlNQdWdkanBGSVNTb0JKVkJhcnN6dWkxaGpkeWd5SlhydVlmZ29vU2hNNnd2CnpmN1Y3VTNjOFdORFhydkJiM2hrdDdDS00vV2VCRStETEovcjdhaDFweHNYNnJWc0poVWQ2Wk5SQ085WlA4MUUKcmE2V1kweWdmUW1BS3RrOVMwUkkwUkhlK2dCOVZMUldQcytBTVdDSGN3RUlPd0lEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQU9rWkluanpxUUFNcTVnNUNZTERJWnh0amdBY3RPVlBSN3pMQmY4d2dHdHRVRldHCmVwa2g4NkRKWU1BZTd0TFhCN0tuZnNTVmZ3bWNSMjMxbzU0dVlPZnhPa015RHhYQWhSTWowQlhKcVRxZk9MNmkKNnZVQW5GNlFqdkxmVDZ4MkE3bXQ4OWEzYVZyUkl6aTdtMVFyR21BTHBKMitsTzdEZW5vaHBjd1NWN3N2OVZnRAovTEZTYzR0YmFJTGtJa0FoMzNsMTJtZUh3d3ZYOEt0S3M2K0laWFdrN0NMTjlKSUErQVRmMU9jRW9pNmxDdWRVClRCaTNPcS93M0pMaVpXTDUxZ0REZW41T1pNV0NqTERTNEZwcStHQU1kMEhkaFBsbVM1ajY2b0tUaElkbU5MM1AKMmdDSWlETzNFa1orQ0ZJQUhRZUVnMXRFd0hCcTA3UUhsU1BNWU0wPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K 
  groups:
  - system:masters
  - system:authenticated
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
