apiVersion: v1
kind: Pod
metadata:
  name: net
  labels:
    app: net
spec:
  containers:
  - image: jupyterhub/k8s-network-tools:1.2.0
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: net
  restartPolicy: Always
