# Open할 service 정의
apiVersion: v1
kind: Service
metadata:
  name: external-data #name을 가지고 endpoint 와 연결 합니다.
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
---
#service와 연결할 endpoint 정의
apiVersion: v1
kind: Endpoints
metadata:
  name: external-data #name을 가지고 service 와 연결 합니다.
subsets:
  - addresses:
      - ip: 192.168.0.26 #연결할 IP 주소
    ports:
      - name: http
        port: 80
---
#endpoint와 연결할 loadbalancer 정의
apiVersion: v1
kind: Service
metadata:
  name: lb-endpoint
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
