apiVersion: v1
kind: Pod
metadata:
  labels:
    run: node-selector
  name: node-selector
spec:
  containers:
    - image: nginx
      name: node-selector
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
