apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-affinity
  name: node-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-affinity
  strategy: {}
  template:
    metadata:
      labels:
        app: node-affinity
    spec:
      containers:
      - image: nginx
        name: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values:
                  - large
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - large
            - weight: 50
              preference:
                matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - medium
      
        