apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: schedule-nginx-1
  name: schedule-nginx-1
spec:
  containers:
  - image: nginx
    name: schedule-nginx-1
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: worker1
status: {}
