apiVersion: v1
kind: Pod
metadata:
  labels:
    run: toleration-pod
  name: toleration-pod
spec:
  containers:
  - image: nginx
    name: toleration-pod
    resources: {}
  tolerations:
  - key: app
    operator: "Equal"
    value: blue
    effect: "NoExecute"
  - key: app
    operator: "Equal"
    value: red
    effect: "NoSchedule"


