apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-nginx
  template:
    metadata:
      labels:
        app: cluster-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
