apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-ubuntu
  name: secret-ubuntu
spec:
  containers:
  - image: ubuntu
    name: secret-ubuntu
    envFrom:
      - secretRef:
          name: mysecret
    command: ["sleep"]
    args: ["infinity"]
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
