apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-volume-ubuntu
  name: secret-volume-ubuntu
spec:
  containers:
  - image: ubuntu
    name: secret-volume-ubuntu
    command: ["sleep"]
    args: ["infinity"]
    volumeMounts:
      - name: app-secret-volume
        mountPath: "/config"
        readOnly: true
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
  volumes:
    - name: app-secret-volume
      secret:
        secretName: mysecret
